### ISSUE TITLE
What to do with dart-rss?

### ISSUE THREAD

**Issue by Feichtmeier** [amugofjava/podcast_search#13]
Hi @amugofjava 

As you might remember I use your nice package for the ubuntu app I created

To upgrade musicpod to dart3 and flutter 3.10 I need your package to be updated
To update your package we need dart-rss to be updated
Which I did here https://github.com/Feichtmeier/dart-rss
but the maintainer does not respond and is inactive since years so I doubt this PR will be merged

Since your package is published you can not use a git ref as dep (my fork of dart-rss)
what is your suggestion to do now?

**Comment by amugofjava** [comment]
Hi @Feichtmeier,

Yes, this is a problem. I am having to use a branch directly in my app as I cannot package the changes I've made in `podcast_search` to pub.dev. I have tried to reach the dev to offer to be a maintainer, but I think this repo has been abandoned.

I think we have a couple of options.

1. Use your forks of `podcast_search` and `dart_rss` directly in Musicpod and use git refs in `pubspec.yaml`. This is the approach I am having to take for now for my podcast app. I've not looked into packaging a Flutter app and deploying to the Snap store yet, but Imagine this approach could work - though it's not ideal.
2. We both currently require `dart_rss` so we could work on a new fork together and publish as a new package to pub.dev which in turn can be used by `poscast_search`.

Longer term, I am thinking of building my own RSS parser into `podcast_search` so that I can concentrate on the parts required for podcasting rather than having a general RSS parser. The `dart_rss` package is great and is null safe, but there is a lot ! use in the code - I would like to reduce the amount of null checking.

What do you think?

Musicpod is looking great!

**Comment by Feichtmeier** [comment]
2. Sounds great 😀👍 for now

I could put it into the Ubuntu flutter community repo but I'm unsure about the license
Could we publish my fork as is?

**Comment by Feichtmeier** [comment]
rss
rss.dart

? :D

**Comment by amugofjava** [comment]
rss sounds straight to the point :)

**Comment by Feichtmeier** [comment]
Oh I've went for rss.dart now to match the other ubuntu/canonical packages :) (hope you dont mind)

How to name the package now? Use the old name or create a new one with starting at version 1.0.0 ? before publishing

**Comment by amugofjava** [comment]
dart.rss works for me - though can you have . in package names on pub.dev?

I think v1.0.0 sounds good, but more than happy to go in whatever direction you wish :)

**Comment by Feichtmeier** [comment]
Okay somehow rss was already taken some years ago so i went with 

rss_dart :shrug: 

https://pub.dev/packages/rss_dart

Hope this helps for you :crossed_fingers:

**Comment by amugofjava** [comment]
Great, thank you. I have a PR for for dart-rss which I will change for the new rss_dart. Going forward, shall I continue to submit PRs or are you happy to make me a maintainer on this project? I am happy with either approach.

**Comment by Feichtmeier** [comment]
Added as maintainer :) you can push 🫸
